:uri-teamcity: https://www.jetbrains.com/teamcity/[TeamCity]
:uri-gradle: https://gradle.org/[Gradle]
:uri-github: https://github.com
:uri-shields: https://img.shields.io
:plugin-id: 10872-jmx-support
:plugin-name: teamcity-jmx-plugin
:uri-project: {uri-github}/rodm/{plugin-name}
:uri-download: https://plugins.jetbrains.com/plugin/{plugin-id}
:uri-version: {uri-shields}/jetbrains/plugin/v/{plugin-id}?label=TeamCity%20plugin
:uri-downloads: {uri-shields}/jetbrains/plugin/d/{plugin-id}?label=Downloads
:uri-build-history: {uri-project}/actions
:uri-build-status: {uri-project}/workflows/Build/badge.svg

= JMX Support plugin for TeamCity

The JMX Support plugin exposes attributes of the Build Server, Build Agents and Projects using JMX.

image:{uri-build-status}?branch=master["Build Status", link="{uri-build-history}"]
image:{uri-version}["Version", link={uri-download}]
image:{uri-downloads}["Downloads", link="{uri-download}"]

== How to install

* Download the plugin from {uri-download}[JetBrains TeamCity Plugin Repository]
(see the _Downloads_ section at the bottom of the page).

* Go to the plugin list of your TeamCity installation at `&lt;TeamCity URL&gt;/admin/admin.html?item=plugins` and
click on the link _Upload plugin zip_ to install the downloaded plugin file.

* Restart TeamCity.

== How to use the plugin

* Run the `jvisualvm` command
* Select the TeamCity Server process, it will appear as Tomcat
* Select MBean tab and then expand the node 'com.jetbrains.teamcity'

The following MBeans are made available by the plugin.

* com.jetbrains.teamcity:type=BuildServer
* com.jetbrains.teamcity:type=BuildServer,stats=BuildStatistics
* com.jetbrains.teamcity:type=Agent,name=<agent name>
* com.jetbrains.teamcity:type=Agent,name=<agent name>,stats=BuildStatistics
* com.jetbrains.teamcity:type=Project,name=<project name>
* com.jetbrains.teamcity:type=Project,name=<project name>,stats=BuildStatistics

=== BuildServer attributes

* RegisteredAgents - number of authorized agents currently connected to the server
* UnregisteredAgents - number of authorized agents not currently connected to the server
* UnauthorizedAgents - number of unauthorized agents currently connected to the server
* NumberOfRunningBuilds - number of builds currently running on build agents
* BuildQueueSize - number of builds in the build queue
* FullServerVersion - TeamCity version and build number
* NumberOfRegisteredUsers - number of users registered with the server
* NumberOfProjects - number of projects on the server
* NumberOfBuildTypes - number of build configurations on the server
* CleanupDuration - number of seconds spent performing the last cleanup

=== BuildServer operations

* saveState - saves the plugin's state to a file, this is used by the plugin when the server
is restarted to restore the previous state

=== Agent attributes

* HostName - hostname of the machine running the build agent
* HostAddress - IP address of the machine running the build agent
* Port - port used by the build agent
* OperatingSystemName - operating system and version of the machine running the build agent
* Registered - true if the build agent is connected to the server
* UnregistrationComment - message with the reason for the build agent un-registering
* RegistrationTimestamp - data and time the build agent registered with the server
* LastCommunicationTimestamp - data and time the build agent last communicated with the server
* Enabled - true if the build agent is enabled
* StatusComment - message with the reason for the build agent being enabled or disabled
* Authorized - true if the build agent is authorized
* AuthorizeComment - message with the reason for the build agent being authorized or unauthorized
* CpuBenchmarkIndex - CPU benchmark index of the build agent
* NumberOfCompatibleConfigurations - number of build configurations compatible with the build agent
* NumberOfIncompatibleConfigurations - number of build configurations not compatible with the build agent

=== Project attributes

* NumberOfBuildTypes - number of build configurations excluding sub-projects
* NumberOfBuildTypeTemplates - number of build templates excluding sub-projects
* NumberOfSubProjects - number of sub-projects
* NumberOfVcsRoots - number of VCS roots excluding sub-projects
* NumberOfSuccessfulBuildTypes - number of build configurations with a success status
* NumberOfFailedBuildTypes - number of build configurations with a failed status
* NumberOfPausedBuildTypes - number of build configurations currently paused

=== BuildStatistics attributes

* BuildsStarted - number of builds started
* BuildsFinished - number of builds finished
* BuildsInterrupted - number of builds that were interrupted
* SuccessfulBuilds - number of builds that finished with a success status
* FailedBuilds - number of builds that finished with a failed status
* QueueTime - amount of time in seconds that builds spent in the build queue
* BuildTime - amount of time in seconds that builds spent on a build agent

== How to build the plugin

The build uses {uri-gradle}, the following tasks can be used to build the plugin and deploy it to a
local TeamCity Server for testing.

Build the plugin

    ./gradlew build

The plugin is packaged into a zip file and found in the following directory `build/distributions/`

Start the TeamCity Server and Build Agent

    ./gradlew startTeamcity2018.1

Stop the TeamCity Server and Build Agent

    ./gradlew stopTeamcity2018.1

== How to configure Munin to monitor TeamCity

See the link:config/munin/README.md[README] in the `config/munin` directory.

== Compatibility

The plugin is compatible with TeamCity 2018.1 or later.

== License

This plugin is available under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].
