= JMX Support plugin for TeamCity
:uri-teamcity: https://www.jetbrains.com/teamcity/[TeamCity]
:uri-gradle: https://gradle.org/[Gradle]
:uri-travis-build: https://travis-ci.org/rodm/teamcity-jmx-plugin
:uri-travis-image: https://travis-ci.org/rodm/teamcity-jmx-plugin.svg
:uri-jetbrains-plugin: https://plugins.jetbrains.com/plugin/9004-jmx-plugin
:uri-bintray-plugin: https://bintray.com/rodm/teamcity-plugins/teamcity-jmx-plugin/_latestVersion
:uri-bintray-image: https://api.bintray.com/packages/rodm/teamcity-plugins/teamcity-jmx-plugin/images/download.svg
:uri-teamcity-install-plugin: https://confluence.jetbrains.com/display/TCD10/Installing+Additional+Plugins[Installing Additional Plugins]

The JMX Support plugin exposes attributes of the Build Server and Build Agents using JMX.

image:{uri-travis-image}[Build Status,link={uri-travis-build}]
image:{uri-bintray-image}[Download,link={uri-bintray-plugin}]

== How to install

* Download the plugin from {uri-jetbrains-plugin}[JetBrains TeamCity Plugin Repository] or {uri-bintray-plugin}[Bintray]
(see the _Downloads_ section at the bottom of the page).

* Go to the plugin list of your TeamCity installation at `&lt;TeamCity URL&gt;/admin/admin.html?item=plugins` and
click on the link _Upload plugin zip_ to install the downloaded plugin file.

* Restart TeamCity.

== How to use the plugin

* Run the `jvisualvm` command
* Select the TeamCity Server process, it will appear as Tomcat
* Select MBean tab and then expand the node 'com.jetbrains.teamcity'

The following MBeans are made available by the plugin.

* com.jetbrains.teamcity:type=BuildServer
* com.jetbrains.teamcity:type=BuildServer,stats=BuildStatistics
* com.jetbrains.teamcity:type=Agent,name=<agent name>
* com.jetbrains.teamcity:type=Agent,name=<agent name>,stats=BuildStatistics
* com.jetbrains.teamcity:type=Project,name=<project name>
* com.jetbrains.teamcity:type=Project,name=<project name>,stats=BuildStatistics

=== BuildServer attributes

* RegisteredAgents - number of authorized agents currently connected to the server
* UnregisteredAgents - number of authorized agents not currently connected to the server
* UnauthorizedAgents - number of unauthorized agents currently connected to the server
* NumberOfRunningBuilds - number of builds currently running on build agents
* BuildQueueSize - number of builds in the build queue
* FullServerVersion - TeamCity version and build number
* NumberOfRegisteredUsers - number of users registered with the server
* NumberOfProjects - number of projects on the server
* NumberOfBuildTypes - number of build configurations on the server
* CleanupDuration - number of seconds spent performing the last cleanup

=== Agent attributes

* HostName - hostname of the machine running the build agent
* HostAddress - IP address of the machine running the build agent
* Port - port used by the build agent
* OperatingSystemName - operating system and version of the machine running the build agent
* Registered - true if the build agent is connected to the server
* UnregistrationComment - message with the reason for the build agent un-registering
* RegistrationTimestamp - data and time the build agent registered with the server
* LastCommunicationTimestamp - data and time the build agent last communicated with the server
* Enabled - true if the build agent is enabled
* StatusComment - message with the reason for the build agent being enabled or disabled
* Authorized - true if the build agent is authorized
* AuthorizeComment - message with the reason for the build agent being authorized or unauthorized
* CpuBenchmarkIndex - CPU benchmark index of the build agent
* NumberOfCompatibleConfigurations - number of build configurations compatible with the build agent
* NumberOfIncompatibleConfigurations - number of build configurations not compatible with the build agent

=== Project attributes

* NumberOfBuildTypes - number of build configurations excluding sub-projects
* NumberOfBuildTypeTemplates - number of build templates excluding sub-projects
* NumberOfSubProjects - number of sub-projects
* NumberOfVcsRoots - number of VCS roots excluding sub-projects
* NumberOfSuccessfulBuildTypes - number of build configurations with a success status
* NumberOfFailedBuildTypes - number of build configurations with a failed status
* NumberOfPausedBuildTypes - number of build configurations currently paused

=== BuildStatistics attributes

* BuildsStarted - number of builds started
* BuildsFinished - number of builds finished
* BuildsInterrupted - number of builds that were interrupted
* SuccessfulBuilds - number of builds that finished with a success status
* FailedBuilds - number of builds that finished with a failed status
* QueueTime - amount of time in seconds that builds spent in the build queue
* BuildTime - amount of time in seconds that builds spent on a build agent

== How to build the plugin

The build uses {uri-gradle}, the following tasks can be used to build the plugin and deploy it to a
local TeamCity Server for testing.

Build the plugin

    ./gradlew build

The plugin is packaged into a zip file and found in the following directory `build/distributions/`

Start the TeamCity Server

    ./gradlew startTeamcity10Server

Stop the TeamCity Server

    ./gradlew stopTeamcity10Server

== How to configure Munin to monitor TeamCity

See the link:config/munin/README.md[README] in the `config/munin` directory.

== Compatibility

The plugin is compatible with TeamCity 10.0 and later.

== License

This plugin is available under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].
