
[versions]
teamcity = "1.5.4"

[plugins]
teamcity-server = { id = "io.github.rodm.teamcity-server", version.ref = "teamcity" }
teamcity-environments = { id = "io.github.rodm.teamcity-environments", version.ref = "teamcity" }
sonarqube = { id = "org.sonarqube", version = "4.0.0.2929" }

[libraries]
junit = { module = "junit:junit", version = "4.13.2" }
mockito = { module = "org.mockito:mockito-core", version = "4.11.0" }
